export const mainMenu = [
    {
        id:"100",
        name:"Dashboard",
        icon:"Dashboard",
        path:"/"
    },
    {
        id:"200",
        name:"Categories",
        icon:"Category",
        path:"/categories"
    },
    {
        id:"300",
        name:"Patterns",
        icon:"Apps",
        path:"/patterns"
    },
    {
        id:"400",
        name:"D3",
        icon:"Equalizer",
        path:"/data-viz"
    }
]